## 4.1.1 Embedding 계층
가중치 매개변수로부터 '단어ID에 해당하는 행(벡터)'을 추출하는 계층    
Embedding 계층에 단어 임베딩(분산표현)을 저장하는 것.

## 4.1.2 Embedding 계층 구현

In [1]:
import numpy as np
W = np.arange(21).reshape(7,3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [2]:
W[2]

array([6, 7, 8])

In [3]:
W[5]

array([15, 16, 17])

In [5]:
# 인덱스 4개(1,0,3,0번째)를 한 번에 추출
idx = np.array([1,0,3,0]) 

W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [7]:
import sys
sys.path.append('..')

from common.np import *  # import numpy as np
from common.config import GPU
from common.functions import softmax, cross_entropy_error

In [ ]:
# Embedding 계층의 forward() 메서드

class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

In [8]:
# Embedding 계층의 backrward() 메서드

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None

- np.add.at(A,idx,B)  B를 A의 idx번째 행에 더해줌.