## 3.1.1. 통계기반기법의 문제점
- 통계기반기법은 학습 데이터를 한꺼번에 처리.(배치학습)
- 이에반해 추론기반기법은 학습 데이터의 일부를 사용하여 순차적으로 학습.(미니배치 학습)

## 3.1.2 추론기반기법 개요

## 3.1.3 신경망에서의 단어처리


In [3]:
# 완전연결계층에 의한 변환

import numpy as np

c = np.array([[1,0,0,0,0,0,0]])  #입력
W = np.random.randn(7,3)         #가중치
h = np.matmul(c,W)               #중간노드

print(W)
h

[[-0.5470141   0.87953549 -1.9796911 ]
 [-0.44809081  1.81762624  0.41148296]
 [-0.07859069 -1.49477029  0.85503614]
 [ 0.34582574 -0.00309315  0.67491193]
 [-0.02905162 -1.49241876 -0.61300623]
 [-1.44947315 -0.87474326 -0.17598388]
 [ 0.42399133  1.55493571  0.75736394]]


array([[-0.5470141 ,  0.87953549, -1.9796911 ]])

- 단어 ID가 0인 단어를 원핫 표현으로 표현한 다음 완전연결계층을 통과시켜 변환.
- c는 원핫표혐이므로 단어ID에 대응하는 원소만 1, 그 외에는 0인 벡터
- 앞 코드의 c와 W의 행렬곱은 가중치의 행벡터 하나를 '뽑아낸'것

In [6]:
# MatMul 계층으로 수행

import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

c = np.array([[1,0,0,0,0,0,0]]) 
W = np.random.randn(7,3)     
layer = MatMul(W)
h = layer.forward(c)

print(W)
h

[[ 1.20657833 -0.50646748 -0.68486714]
 [ 0.43408102 -0.65034453 -0.09529475]
 [ 0.94358475  0.49425279 -1.82473031]
 [ 0.51420386 -0.68296673 -0.66574479]
 [ 0.6507916   0.8509618   1.16550071]
 [ 2.23606458  0.67564984  1.5168699 ]
 [-1.29148275 -0.68057908 -1.82222547]]


array([[ 1.20657833, -0.50646748, -0.68486714]])